### ISSUE TITLE
Feature request: Environments

### ISSUE THREAD

**Issue by sorokinvj** [elgorditosalsero/react-gtm-hook#2]
Hey guys, what do you think about adding support for environments? 
https://www.simoahava.com/analytics/better-qa-with-google-tag-manager-environments/

Would love to contribute for that!

Basically it boils down to parsing gtm_auth and gtm_preview params in a slightly different snippet:

```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=<token>&gtm_preview=env-3&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXX);</script>
```

**Comment by elgorditosalsero** [comment]
Hey :)

Yeah, you're welcome, feel free to open a PR and I'll look at it in the next days or I can do it next week probably
