### ISSUE TITLE
Disable logging when using custom environment 

### ISSUE THREAD

**Issue by ZDerekh** [elgorditosalsero/react-gtm-hook#21]
GTM pushes a lot of logging spam into the console when using a custom environment. Is there a way to prevent it?

**Comment by elgorditosalsero** [comment]
Hi @ZDerekh

can you provide more info and a screenshot about the "logging spam"?

Because I don't have any :)

**Comment by elgorditosalsero** [comment]
Closing for the moment due inactivity.
