### ISSUE TITLE
Disable hook conditionally

### ISSUE THREAD

**Issue by olarcher** [elgorditosalsero/react-gtm-hook#37]
I would like to use this library in a larger project. On certain (dev) environments data should not be sent to GTM. Is it possible to disable GTM integration completely, e.g. by checking the value of an environment variable (if GTM_CONTAINER_ID is set then activate, else don't)? To my understanding, since `useGTMDispatch` is a hook it cannot be called conditionally. Is there any way to deactivate the dispatch anyway?

**Comment by doodlemoonch** [comment]
I'd recommend you set up dev/staging/prod GTM environments, it's worth it

**Comment by elgorditosalsero** [comment]
Hi @olarcher, 

as @doodlemoonch suggested, I think you could achieve your goal with GTM environments.

Just disable in some environments the tags where you want data to not be collected 😄

**Comment by olarcher** [comment]
Thanks for the suggestion! Any ideas how this could be solved technically without the need to set up separate GTM envs?

**Comment by elgorditosalsero** [comment]
> Thanks for the suggestion! Any ideas how this could be solved technically without the need to set up separate GTM envs?

I think the only way you have at the moment, is wrapping into ifs the dispatcher based on your environments.

But I can think to add a variable to enable/disable dispatching in the future.

**Comment by elgorditosalsero** [comment]
Hi @olarcher ,

could you try 2.2.0? 
#42 should help you

**Comment by elgorditosalsero** [comment]
Closing due inactivity
