### ISSUE TITLE
How to specify nonce?

### ISSUE THREAD

**Issue by daisy1754** [elgorditosalsero/react-gtm-hook#39]
I want to set up CSP for our site. To do it properly (without using unsafe-eval), I need to specify `nonce` to script tag https://developers.google.com/tag-manager/web/csp

Is there a way to do it via this library?

**Comment by elgorditosalsero** [comment]
Hi @daisy1754,

nope, at the moment this feature of the GTM is not supported.

**Comment by daisy1754** [comment]
are you open to PR? I can try

**Comment by elgorditosalsero** [comment]
> are you open to PR? I can try

@daisy1754 yeah, sure :)
