### ISSUE TITLE
Sever connection when Consent gets disabled

### ISSUE THREAD

**Issue by Pololinger** [elgorditosalsero/react-gtm-hook#53]
Hi, I'm having the issue  that once a user changes the consent from accept to deny to connection to GTM still persists. I have tried overwriting the gtmParms on consent change without success (arbitrary strings or undefined). Collect still pops up in the network tab. 

Also I tried to tie `useGTMDispatch` to the condition of consent being true. Which works but once a consent change happens such as `false`, `true`, `false`, I still get data getting sent to GTM. 

It seems no matter what what I do, once the react gtm hook connects to GTM ,its connection can not be disabled again. 
Has anyone ever run into this problem or knows a way out?

**Comment by elgorditosalsero** [comment]
Hey @Pololinger, is this still happening?

Sorry for the late answer.

**Comment by Pololinger** [comment]
No worries. As a workaround we now just reload the page, if the consent gets changed from accept to deny.
