### ISSUE TITLE
react-hooks/exhaustive-deps will warn due to init not being listed as a dependency.

### ISSUE THREAD

**Issue by jafin** [elgorditosalsero/react-gtm-hook#6]
Using the example in the codebase, when I add eslint + react-hooks/exhaustive-deps rule and run a lint check
Will receive warning due to `init` not being listed as a dependency in `useEffect`:

```
11:5  warning  React Hook React.useEffect has a missing dependency: 'init'. 
Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

```ts
  React.useEffect(
    () => init({ id: 'GTM-xxxx', dataLayer: { customInitValue: 'imCustom' }, dataLayerName: 'customDL' }),
    []
  )
```
If init is added as a dep, then a circular loop will occur.

I created a PR to see if that is the fix, #7

**Comment by elgorditosalsero** [comment]
Thanks.

Fixed with #7
