### ISSUE TITLE
Possibility to add multiple tag-ids

### ISSUE THREAD

**Issue by kmrozewski** [elgorditosalsero/react-gtm-hook#61]
I would be great to add a possibility to supply multiple tag-ids. There's `@tymate/react-gtm` which does that, but the lib is written only in js

**Comment by elgorditosalsero** [comment]
Hey @kmrozewski, do you want to implement the feature?

I'll try to find someone to take a look at this!

Sorry for the late answer.

**Comment by kmrozewski** [comment]
Hi, I already forked your repository and added the feature. Unfortunately I had to change the owner of the fork (to my previous company) so I don't have access to it anymore.

**Comment by oktalk** [comment]
Any possibility of resurrecting this? I also have a need for adding in multiple GTM containers.
