### ISSUE TITLE
Remove "console.log('CUSTOOOOM DOMAIN', customDomain);" within initGTM

### ISSUE THREAD

**Issue by florianmatz** [elgorditosalsero/react-gtm-hook#66]
In Line 49 of GoogleTagManager.ts

a quite scandalous console.log() happens.

https://github.com/elgorditosalsero/react-gtm-hook/blob/d649f16bd04698a0f6b10ead2958bd1787c08dff/src/utils/GoogleTagManager.ts#L49

Could it be removed?

**Comment by florianmatz** [comment]
@thebiltheory It seems, that you haven't remove a development logging?

**Comment by thebiltheory** [comment]
@florianmatz oops😂. It sure can. Is it bothering you for now?

**Comment by florianmatz** [comment]
@thebiltheory :P - kind of - I want to use the package in one of our client portals and it feels a bit glitchy to have strange logs in my business prod code :)

I've seen, there is already an open PR for that. @elgorditosalsero do you mind approving it?

**Comment by elgorditosalsero** [comment]
Closing due #64
