### ISSUE TITLE
Support custom gtm.js file name

### ISSUE THREAD

**Issue by pkulcsarnr** [elgorditosalsero/react-gtm-hook#75]
One of the main reason to move to server side GTM is to avoid being blocked by browsers and adblocks. For this reason it is possible to change the custom domain and the name of the file as well. For example tracking.mydomain.com/t.js. For now it is not possible to set the name of the file in this package.

**Comment by pkulcsarnr** [comment]
Implemented the possible solution in this PR: https://github.com/elgorditosalsero/react-gtm-hook/pull/76

**Comment by pkulcsarnr** [comment]
@elgorditosalsero Can you please check the implementation?

**Comment by elgorditosalsero** [comment]
Hey @pkulcsarnr, #76 approved and merged 😄
