### ISSUE TITLE
typescript error when upgrading to version v2.7.1

### ISSUE THREAD

**Issue by TheWalkingDad3** [elgorditosalsero/react-gtm-hook#79]
Disclaimer: this is my first issue report so I hope I can provide you the information that is needed ...

After the upgrade to version 2.7.1 I got an error when building my typescript application.

> Type error: Argument of type '{ event: string; value: string; }' is not assignable to parameter of type 'ISendToGTM'.
  Object literal may only specify known properties, and 'event' does not exist in type 'ISendToGTM'.

even if I use the demo-code it is not working:
`const sendDataToGTM = useGTMDispatch();
sendDataToGTM({ event: 'awesomeButtonClicked', value: 'imAwesome' });`

thank you very much, Tobias

**Comment by elgorditosalsero** [comment]
Hi @TheWalkingDad3, it should be fixed now with the 2.7.2 release, feel free to re-open if not working.

**Comment by TheWalkingDad3** [comment]
works now perfect, thank you very much for your help :)
