### ISSUE TITLE
Can't see any history tags with basic implementation ?

### ISSUE THREAD

**Issue by hiahmedhameed** [elgorditosalsero/react-gtm-hook#9]
Hey,

I just implemented basic configuration as follow:

```typescript

[...]
const {init} = useGTM();

useEffect(() => {
  init({id: environment.gtmId});
}, [init])
```

We are tracking `History API` of the browser for SPA. But can't see any tags of my pages!

Do i miss something ?

**Comment by elgorditosalsero** [comment]
Hi,

the `History Change` trigger is configured on your GTM?

Will do some test and check into this.

**Comment by hiahmedhameed** [comment]
Hi @elgorditosalsero 

Yep, i already did the configuration. When using `react-gtm-module`, it works fine but with this module it does not show anything.

Thanks.

**Comment by elgorditosalsero** [comment]
Hi @hiahmedhameed,

I've done some tests and you're right, I'm 👀  into this.

And next weeks I, probably, do a refactor to the hook 🎉

**Comment by elgorditosalsero** [comment]
Hi @hiahmedhameed,

I've done some tests and you're right, I'm 👀  into this.

And next weeks I, probably, will do some refactor to the hook 🎉

**Comment by elgorditosalsero** [comment]
> Hi @hiahmedhameed,
> 
> I've done some tests and you're right, I'm 👀 into this.
> 
> And next weeks I, probably, will do some refactor to the hook 🎉

Hi @hiahmedhameed 

with the [latest release](https://github.com/elgorditosalsero/react-gtm-hook/releases/tag/2.0.0), I've fixed the issue of the history navigation.

You could see also a live example [here](https://elgorditosalsero-react-gtm-hook.netlify.app/)

Try to update the hook and follow the new snippets.
Let me know 💯

**Comment by elgorditosalsero** [comment]
I'm closing the issue due to inactivity.

@hiahmedhameed feel free to reopen if you still have the issue with version 2.x.
